apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    component: rabbitmq
    stack: local
  ports:
    - protocol: TCP
      port: 5672
      nodePort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    component: server
    stack: local
  ports:
    - protocol: TCP
      port: 4000
      nodePort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    component: web
    stack: local
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 8080
---
apiVersion: v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: "0%"
      maxSurge: 1
  selector:
    matchLabels:
      component: web
      stack: local
  template:
    metadata:
      name: rabbitmq
      labels:
        component: rabbitmq
        stack: local
        logs: "true"
        deployTime: {{DEPLOY_TIME}}
    spec:
      containers:
        - name: web
          image: web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: "0%"
      maxSurge: 1
  selector:
    matchLabels:
      component: server
      stack: local
  spec:
    containers:
      - name: server
        image: server
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
      - name: consumer
        image: consumer
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: "0%"
      maxSurge: 1
  selector:
    matchLabels:
      component: rabbitmq
      stack: local
  spec:
    containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5672